In [87]:
def findSum(tuples, targetSum):
    result = []
    
    for pair in tuples:
        if sum(pair) == targetSum:
            result.append(pair)
    
    return result

tuples = []
n = int(input("Enter the number of tuples: "))

for i in range(n):
    a = int(input(f"Enter the first integer for tuple {i+1}: "))
    b = int(input(f"Enter the second integer for tuple {i+1}: "))
    tuples.append((a, b))

print(f"\n\nInput tuple is : {tuples}\n")
targetSum = int(input("Enter the target sum: "))
result = findSum(tuples, targetSum)
print("Pairs with the target sum:", result)


Enter the number of tuples:  11
Enter the first integer for tuple 1:  1
Enter the second integer for tuple 1:  2
Enter the first integer for tuple 2:  2
Enter the second integer for tuple 2:  3
Enter the first integer for tuple 3:  4
Enter the second integer for tuple 3:  5
Enter the first integer for tuple 4:  6
Enter the second integer for tuple 4:  7
Enter the first integer for tuple 5:  8
Enter the second integer for tuple 5:  9
Enter the first integer for tuple 6:  1
Enter the second integer for tuple 6:  9
Enter the first integer for tuple 7:  2
Enter the second integer for tuple 7:  8
Enter the first integer for tuple 8:  3
Enter the second integer for tuple 8:  7
Enter the first integer for tuple 9:  4
Enter the second integer for tuple 9:  6
Enter the first integer for tuple 10:  6
Enter the second integer for tuple 10:  4
Enter the first integer for tuple 11:  5
Enter the second integer for tuple 11:  5




Input tuple is : [(1, 2), (2, 3), (4, 5), (6, 7), (8, 9), (1, 9), (2, 8), (3, 7), (4, 6), (6, 4), (5, 5)]



Enter the target sum:  10


Pairs with the target sum: [(1, 9), (2, 8), (3, 7), (4, 6), (6, 4), (5, 5)]


In [ ]:
(1,2),(2,3),(4,5),(6,7),(8,9),(1,9),(2,8),(3,7),(4,6),(6,4),(5,5)]

In [33]:
import numpy 

def diagonalSum(arr):
    
    diagonalSum = 0
    for i in range(len(arr)):
        diagonalSum += arr[i, i]
    return diagonalSum
n = int(input("Please enter the dimension of  square array: "))
arrayElements = []
print("Enter array elements :")
for i in range(n):
    listElements=[]
    for j in range(n):
        a=int(input())
        listElements.append(a)
    arrayElements.append(listElements)
        

print(arrayElements)
arr = numpy.array(arrayElements)
print("\nThe array is:")
print(arr)
result = diagonalSum(arr)
print(f"\nThe sum of the diagonal elements is: {result}")

Please enter the dimension of  square array:  3


Enter array elements :


 1
 2
 3
 4
 5
 6
 7
 8
 9


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

The array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The sum of the diagonal elements is: 15


In [90]:
def mergeDicts(dict1, dict2):
    merged = {}
    for key in dict1:
        if key in dict2:
            merged[key] = [dict1[key], dict2[key]]
        else:
            merged[key] = dict1[key]
    
    for key in dict2:
        if key not in merged:
            merged[key] = dict2[key]

    return merged
dict1 = {
    'Suchi': 100,
    'Deya': 80,
    'Srabanti':85
}

dict2 = {
    'Suchi': 95,
    'Deya': 85,
    'Srabanti':89,
    'Sumi': 70
}
outputs = mergeDicts(dict1, dict2)
print(f"Dictionary1 is : {dict1}\n")
print(f"Dictionary2 is : {dict2}\n")
print(f"Merged dictionary is : {outputs}")


Dictionary1 is : {'Suchi': 100, 'Deya': 80, 'Srabanti': 85}

Dictionary2 is : {'Suchi': 95, 'Deya': 85, 'Srabanti': 89, 'Sumi': 70}

Merged dictionary is : {'Suchi': [100, 95], 'Deya': [80, 85], 'Srabanti': [85, 89], 'Sumi': 70}


***Time Complexity:-***
Iterating through dictionary1: The first loop runs in 
𝑂
(
3
)
, where 
3
is the number of keys in dictionary1.
Iterating through dictionary2: The second loop runs in 
𝑂
(
4
)
, where 
4 is the number of keys in dictionary2.
Thus, the overall time complexity of the merge operation is O(3+4),  
is equal to o(7). This approach efficiently handles the merging of two dictionaries.